modLoader="javafml" #mandatory
loaderVersion="[35,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.
[[mods]] #mandatory
modId="wcfarmlife" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Wings and Claws: Farm Life" #mandatory
credits="Tazz, Coda" #optional
description='''
Placeholder description.'''